# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = [
    "Author Name <jason.aung@tollgroup.com>",
]

# The title and description fields are primarily for displaying extension info in the UI
title = 'Unilever Extension'
description = "The simplest python UI extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
# repository = "https://github.com/example/repository_name"

# One of categories for the UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extension manager. It is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}
"omni.kit.manipulator.viewport" = {}
"omni.kit.viewport.registry" = {}
"omni.ui.scene" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = {}
"omni.usd" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.popup_dialog" = {}


# Main python module this extension provides, it will be publicly available as "import my_company.my_python_ui_extension".
[[python.module]]
name = "my_company.my_python_ui_extension"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
[python.pipapi]
requirements = [
    "requests",
    "openai",
    "pandas",
    "langchain",
    "paho-mqtt"
]
#"langchain"
use_online_index = true

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture"
]
